# Generated by Django 4.2 on 2024-01-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userlogin_alter_contentmodal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodal',
            name='primaryKey',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
